# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_sharecodes

on:
  workflow_dispatch:
  schedule:
    - cron: '5 16 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_sharecodes
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: duandaxei/jd_scripts
      - name: '运行 【互助码自动上车】'
        run: |
          chmod +x jd_sharecodes.sh
          ./.github/jd_sharecodes.sh
        env:
          PETSHARECODES: ${{ secrets.PETSHARECODES }}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES }}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
          JXFACTORY_SHARECODES: ${{ secrets.JXFACTORY_SHARECODES }}